spring:
  application:
    name: dynamic-security-analysis-server

  cloud:
    function:
      definition: consumeRun;consumeCancel
    stream:
      bindings:
        consumeRun-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}dsa.run
          group: dsaGroup
          consumer:
            concurrency: 2
            max-attempts: 1
        publishRun-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}dsa.run
        publishResult-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}dsa.result
        consumeCancel-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}dsa.cancel
        publishCancel-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}dsa.cancel
        publishStopped-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}dsa.stopped
        publishCancelFailed-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}dsa.cancelfailed
      output-bindings: publishRun-out-0;publishResult-out-0;publishCancel-out-0;publishStopped-out-0;publishCancelFailed-out-0
      rabbit:
        bindings:
          consumeRun-in-0:
            consumer:
              auto-bind-dlq: true
              dead-letter-exchange: ${powsybl-ws.rabbitmq.destination.prefix:}dsa.run.dlx
              dead-letter-queue-name: ${powsybl-ws.rabbitmq.destination.prefix:}dsa.run.dlx.dlq
              dead-letter-exchange-type: topic
              quorum:
                enabled: true
                delivery-limit: 2

powsybl:
  services:
    network-store-server:
      preloading-strategy: COLLECTION

powsybl-ws:
  database:
    name: dynamicsecurityanalysis

# default values for dynamic security analysis providers is "Dynawo"
dynamic-security-analysis:
  default-provider: Dynawo
